/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

//SQL and JAVA
import com.itextpdf.kernel.colors.DeviceRgb;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.*;
import java.util.Date;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;


// iText
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.*;
import com.itextpdf.layout.borders.*;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.io.image.*;
import com.itextpdf.layout.properties.HorizontalAlignment;

import java.io.File;

/**
 *
 * @author Arthur Dias, Leonardo
 */
public class TelaCarregamento extends javax.swing.JFrame {

    private Connection conn;
    // Variáveis Banco de dados - PostGreSQL
    private static final String table = "acic_table";
    private static final String database = "acicDATA";
    private static final String URL = "jdbc:postgresql://localhost:5432/"+database;  // URL do banco (Não altere se deixar sistema local)
    private static final String USER = "postgres";  // Usuário do banco
    private static final String PASSWORD = "cupqj11";
    /**
     * Creates new form TelaPrincipal
     */
    public TelaCarregamento() {
        initComponents();
        // Conexão com banco de dados
        // PostGreSQL Connection
        try {
            Date c = new Date();
            System.out.println(c.getTime());
            // Estabelece a conexão com o banco
            conn = DriverManager.getConnection(URL, USER, PASSWORD);
            System.out.println("Conectado ao banco de dados com sucesso!");
            carregarServicos();
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Erro ao conectar ao banco de dados");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojeru_san.complementos.RSTableMetro();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Saida = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBservicos = new rojeru_san.complementos.RSTableMetro();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBservicos1 = new rojeru_san.complementos.RSTableMetro();
        jScrollPane4 = new javax.swing.JScrollPane();
        TBservicos2 = new rojeru_san.complementos.RSTableMetro();
        jScrollPane5 = new javax.swing.JScrollPane();
        TBservicos3 = new rojeru_san.complementos.RSTableMetro();
        jScrollPane6 = new javax.swing.JScrollPane();
        TBservicos4 = new rojeru_san.complementos.RSTableMetro();
        jScrollPane7 = new javax.swing.JScrollPane();
        TBservicos5 = new rojeru_san.complementos.RSTableMetro();
        jScrollPane8 = new javax.swing.JScrollPane();
        TBservicos6 = new rojeru_san.complementos.RSTableMetro();
        jScrollPane9 = new javax.swing.JScrollPane();
        TBservicos7 = new rojeru_san.complementos.RSTableMetro();
        jScrollPane10 = new javax.swing.JScrollPane();
        TBservicos8 = new rojeru_san.complementos.RSTableMetro();
        jScrollPane11 = new javax.swing.JScrollPane();
        TBservicos9 = new rojeru_san.complementos.RSTableMetro();
        jScrollPane12 = new javax.swing.JScrollPane();
        TBservicos10 = new rojeru_san.complementos.RSTableMetro();
        jScrollPane13 = new javax.swing.JScrollPane();
        TBservicos11 = new rojeru_san.complementos.RSTableMetro();
        jScrollPane14 = new javax.swing.JScrollPane();
        TBservicos12 = new rojeru_san.complementos.RSTableMetro();
        jScrollPane15 = new javax.swing.JScrollPane();
        TBservicos13 = new rojeru_san.complementos.RSTableMetro();
        jScrollPane16 = new javax.swing.JScrollPane();
        TBservicos14 = new rojeru_san.complementos.RSTableMetro();
        jScrollPane17 = new javax.swing.JScrollPane();
        TBservicos15 = new rojeru_san.complementos.RSTableMetro();
        jScrollPane18 = new javax.swing.JScrollPane();
        TBservicos16 = new rojeru_san.complementos.RSTableMetro();

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(rSTableMetro1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de serviços");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 194, 77));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consulta de Serviços");

        Saida.setBackground(new java.awt.Color(255, 255, 255));
        Saida.setFont(new java.awt.Font("Arial Black", 0, 35)); // NOI18N
        Saida.setForeground(new java.awt.Color(255, 255, 255));
        Saida.setText("<");
        Saida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Saida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaidaMouseClicked(evt);
            }
        });

        jButton1.setText("Baixar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(413, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(340, 340, 340))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(394, 394, 394)))
                .addComponent(Saida)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Saida)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))))
        );

        TBservicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TBservicos);
        if (TBservicos.getColumnModel().getColumnCount() > 0) {
            TBservicos.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        TBservicos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos1.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos1.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos1.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicos1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TBservicos1);
        if (TBservicos1.getColumnModel().getColumnCount() > 0) {
            TBservicos1.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos1.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos1.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos1.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos1.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos1.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        TBservicos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos2.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos2.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos2.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicos2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TBservicos2);
        if (TBservicos2.getColumnModel().getColumnCount() > 0) {
            TBservicos2.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos2.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos2.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos2.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos2.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos2.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        TBservicos3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos3.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos3.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos3.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicos3MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(TBservicos3);
        if (TBservicos3.getColumnModel().getColumnCount() > 0) {
            TBservicos3.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos3.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos3.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos3.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos3.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos3.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        TBservicos4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos4.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos4.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos4.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicos4MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(TBservicos4);
        if (TBservicos4.getColumnModel().getColumnCount() > 0) {
            TBservicos4.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos4.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos4.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos4.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos4.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos4.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        TBservicos5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos5.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos5.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos5.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicos5MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(TBservicos5);
        if (TBservicos5.getColumnModel().getColumnCount() > 0) {
            TBservicos5.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos5.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos5.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos5.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos5.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos5.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        TBservicos6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos6.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos6.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos6.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicos6MouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(TBservicos6);
        if (TBservicos6.getColumnModel().getColumnCount() > 0) {
            TBservicos6.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos6.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos6.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos6.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos6.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos6.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        TBservicos7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos7.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos7.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos7.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicos7MouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(TBservicos7);
        if (TBservicos7.getColumnModel().getColumnCount() > 0) {
            TBservicos7.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos7.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos7.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos7.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos7.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos7.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        TBservicos8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos8.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos8.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos8.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicos8MouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(TBservicos8);
        if (TBservicos8.getColumnModel().getColumnCount() > 0) {
            TBservicos8.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos8.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos8.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos8.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos8.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos8.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        TBservicos9.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos9.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos9.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos9.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicos9MouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(TBservicos9);
        if (TBservicos9.getColumnModel().getColumnCount() > 0) {
            TBservicos9.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos9.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos9.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos9.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos9.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos9.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        TBservicos10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos10.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos10.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos10.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicos10MouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(TBservicos10);
        if (TBservicos10.getColumnModel().getColumnCount() > 0) {
            TBservicos10.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos10.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos10.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos10.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos10.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos10.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        TBservicos11.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos11.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos11.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos11.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicos11MouseClicked(evt);
            }
        });
        jScrollPane13.setViewportView(TBservicos11);
        if (TBservicos11.getColumnModel().getColumnCount() > 0) {
            TBservicos11.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos11.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos11.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos11.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos11.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos11.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        TBservicos12.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos12.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos12.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos12.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicos12MouseClicked(evt);
            }
        });
        jScrollPane14.setViewportView(TBservicos12);
        if (TBservicos12.getColumnModel().getColumnCount() > 0) {
            TBservicos12.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos12.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos12.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos12.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos12.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos12.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        TBservicos13.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos13.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos13.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos13.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicos13MouseClicked(evt);
            }
        });
        jScrollPane15.setViewportView(TBservicos13);
        if (TBservicos13.getColumnModel().getColumnCount() > 0) {
            TBservicos13.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos13.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos13.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos13.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos13.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos13.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        TBservicos14.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos14.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos14.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos14.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicos14MouseClicked(evt);
            }
        });
        jScrollPane16.setViewportView(TBservicos14);
        if (TBservicos14.getColumnModel().getColumnCount() > 0) {
            TBservicos14.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos14.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos14.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos14.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos14.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos14.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        TBservicos15.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos15.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos15.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos15.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicos15MouseClicked(evt);
            }
        });
        jScrollPane17.setViewportView(TBservicos15);
        if (TBservicos15.getColumnModel().getColumnCount() > 0) {
            TBservicos15.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos15.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos15.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos15.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos15.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos15.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        TBservicos16.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "SERVIÇO", "DESCRIÇÃO", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBservicos16.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        TBservicos16.setColorBordeFilas(new java.awt.Color(0, 204, 255));
        TBservicos16.setColorBordeHead(new java.awt.Color(255, 255, 255));
        TBservicos16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBservicos16MouseClicked(evt);
            }
        });
        jScrollPane18.setViewportView(TBservicos16);
        if (TBservicos16.getColumnModel().getColumnCount() > 0) {
            TBservicos16.getColumnModel().getColumn(0).setMinWidth(30);
            TBservicos16.getColumnModel().getColumn(0).setMaxWidth(9999);
            TBservicos16.getColumnModel().getColumn(1).setMinWidth(200);
            TBservicos16.getColumnModel().getColumn(1).setMaxWidth(9999);
            TBservicos16.getColumnModel().getColumn(3).setMinWidth(150);
            TBservicos16.getColumnModel().getColumn(3).setMaxWidth(99999);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane3)
            .addComponent(jScrollPane4)
            .addComponent(jScrollPane5)
            .addComponent(jScrollPane6)
            .addComponent(jScrollPane7)
            .addComponent(jScrollPane8)
            .addComponent(jScrollPane9)
            .addComponent(jScrollPane10)
            .addComponent(jScrollPane11)
            .addComponent(jScrollPane12)
            .addComponent(jScrollPane13)
            .addComponent(jScrollPane14)
            .addComponent(jScrollPane15)
            .addComponent(jScrollPane16)
            .addComponent(jScrollPane17)
            .addComponent(jScrollPane18)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TBservicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicosMouseClicked
       if(TBservicos.getSelectedRow() != -1){/*
        jvID.setText(TBservicos.getValueAt(TBservicos.getSelectedRow(), 0).toString());
        jvservico.setText(TBservicos.getValueAt(TBservicos.getSelectedRow(), 1).toString());
        jvdescricao.setText(TBservicos.getValueAt(TBservicos.getSelectedRow(), 2).toString());
        jvdata.setText(TBservicos.getValueAt(TBservicos.getSelectedRow(), 3).toString());
*/
         }
    }//GEN-LAST:event_TBservicosMouseClicked

    private void SaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaidaMouseClicked
        setVisible(false);
        new tela_interativa().setVisible(true);
    }//GEN-LAST:event_SaidaMouseClicked

    private void TBservicos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBservicos1MouseClicked

    private void TBservicos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicos2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBservicos2MouseClicked

    private void TBservicos3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicos3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBservicos3MouseClicked

    private void TBservicos4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicos4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBservicos4MouseClicked

    private void TBservicos5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicos5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBservicos5MouseClicked

    private void TBservicos6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicos6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBservicos6MouseClicked

    private void TBservicos7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicos7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBservicos7MouseClicked

    private void TBservicos8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicos8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBservicos8MouseClicked

    private void TBservicos9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicos9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBservicos9MouseClicked

    private void TBservicos10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicos10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBservicos10MouseClicked

    private void TBservicos11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicos11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBservicos11MouseClicked

    private void TBservicos12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicos12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBservicos12MouseClicked

    private void TBservicos13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicos13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBservicos13MouseClicked

    private void TBservicos14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicos14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBservicos14MouseClicked

    private void TBservicos15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicos15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBservicos15MouseClicked

    private void TBservicos16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBservicos16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TBservicos16MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pdf();
    }//GEN-LAST:event_jButton1ActionPerformed

   
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCarregamento().setVisible(true);
            }
        });
    }

    
    public Connection getConnection() {
        return conn;
    }
    
    
    public void pdf()
    {
        String homeDirectory = System.getProperty("user.home");
        String documentsDirectory = homeDirectory + File.separator + "Documents";
        File gacicFolder = new File(documentsDirectory, "SCACIC");
        if (!gacicFolder.exists()) {
            System.out.println(gacicFolder);
            gacicFolder.mkdir();
            System.out.println(gacicFolder);
        }
        LocalDateTime c = LocalDateTime.now();
        DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd-MM-yyyy_HH_mm_ss");
        String dataHoraFormatada = c.format(formatador);
        String dest = gacicFolder+"/relatorio_"+dataHoraFormatada+".pdf";
        String destImg = "src/imagens/aciclog.png";
        String sql = "SELECT id, service, descri, data FROM " + table + " WHERE id_cad="+Integer.valueOf(view.iddd);

        // Cria um documento PDF
        try (
            // Conexão com o banco de dados
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql)
        )
        {
            float widPDF[] = {85f, 300f, 100f};
            // Cria o PdfWriter
            PdfWriter writer = new PdfWriter(new File(dest));
            // Cria o PdfDocument
            PdfDocument pdf = new PdfDocument(writer);
            // Cria um Document para adicionar elementos
            Document document = new Document(pdf);

            // Adiciona um parágrafo ao documento
            ImageData data = ImageDataFactory.create(destImg);
            Image imagem1 = new Image(data);
            document.add(imagem1.setHorizontalAlignment(HorizontalAlignment.CENTER));
            document.add(new Paragraph(""));
            document.add(new Paragraph("Relatório").setBold().setFontSize(20).setTextAlignment(TextAlignment.CENTER));
      
            
            Table table = new Table(widPDF);
            
            Border bord1 = new GrooveBorder(3);
            
            Table threeTab = new Table(widPDF);
            threeTab.setBackgroundColor(new DeviceRgb(23,23,23), 0.6f);
            threeTab.addCell(new Cell().add(new Paragraph("Serviço")).setFontColor(new DeviceRgb(255,255,255)).setBorder(Border.NO_BORDER).setTextAlignment(TextAlignment.CENTER));
            threeTab.addCell(new Cell().add(new Paragraph("Descrição")).setFontColor(new DeviceRgb(255,255,255)).setBorder(Border.NO_BORDER).setTextAlignment(TextAlignment.CENTER));
            threeTab.addCell(new Cell().add(new Paragraph("Data")).setFontColor(new DeviceRgb(255,255,255)).setBorder(Border.NO_BORDER).setTextAlignment(TextAlignment.CENTER));
            document.add(threeTab.setHorizontalAlignment(HorizontalAlignment.CENTER));
            
            while (rs.next())
            {
                table.addCell(new Cell().add(new Paragraph(rs.getString("service"))));
                table.addCell(new Cell().add(new Paragraph(rs.getString("descri"))));
                table.addCell(new Cell().add(new Paragraph(rs.getDate("data").toString())));
            }
            document.add(table.setHorizontalAlignment(HorizontalAlignment.CENTER));
            document.add(new Paragraph("Este relatório é gerado automaticamente pelo sistema").setFontSize(10).setTextAlignment(TextAlignment.CENTER));
            // Fecha o documento
            document.close();
            System.out.println("PDF criado com sucesso em: " + dest);
            JOptionPane.showMessageDialog(null, "Relatório Salvo em "+dest);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    // Atualizar tabela
    public void carregarServicos() {
        // Ajustar nome das colunas se necessário
        String sql = "SELECT id, service, descri, data FROM " + table + " WHERE id_cad="+Integer.valueOf(view.iddd);
        try (Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery(sql))
        {
            DefaultTableModel tbprodutos = (DefaultTableModel) TBservicos4.getModel();
            tbprodutos.setRowCount(0); // Limpa a tabela antes de adicionar os dados
                
            while (rs.next())
            {
                Object[] dados =
                {
                    rs.getInt("id"),
                    rs.getString("service"),
                    rs.getString("descri"),
                    rs.getDate("data")
                };
                
                tbprodutos.addRow(dados);
            }
        }
        catch (SQLException e)
        {
            System.out.println("Erro ao carregar serviços");
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Saida;
    private rojeru_san.complementos.RSTableMetro TBservicos;
    private rojeru_san.complementos.RSTableMetro TBservicos1;
    private rojeru_san.complementos.RSTableMetro TBservicos10;
    private rojeru_san.complementos.RSTableMetro TBservicos11;
    private rojeru_san.complementos.RSTableMetro TBservicos12;
    private rojeru_san.complementos.RSTableMetro TBservicos13;
    private rojeru_san.complementos.RSTableMetro TBservicos14;
    private rojeru_san.complementos.RSTableMetro TBservicos15;
    private rojeru_san.complementos.RSTableMetro TBservicos16;
    private rojeru_san.complementos.RSTableMetro TBservicos2;
    private rojeru_san.complementos.RSTableMetro TBservicos3;
    private rojeru_san.complementos.RSTableMetro TBservicos4;
    private rojeru_san.complementos.RSTableMetro TBservicos5;
    private rojeru_san.complementos.RSTableMetro TBservicos6;
    private rojeru_san.complementos.RSTableMetro TBservicos7;
    private rojeru_san.complementos.RSTableMetro TBservicos8;
    private rojeru_san.complementos.RSTableMetro TBservicos9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private rojeru_san.complementos.RSTableMetro rSTableMetro1;
    // End of variables declaration//GEN-END:variables
}
