/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Arthur Dias
 */
public class view extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jPanel2 = new javax.swing.JPanel();
        Saida = new javax.swing.JLabel();
        CPlembrarsenha = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CPsenha = new app.bolivia.swing.JCTextField();
        CPlogin = new app.bolivia.swing.JCTextField();
        Cadastro = new rojerusan.RSMaterialButtonCircle();
        Loguin = new rojerusan.RSMaterialButtonCircle();
        jLabel11 = new javax.swing.JLabel();
        rSPanelImage2 = new rojerusan.RSPanelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 225));
        jLabel2.setText("DESENVOLVIMENTO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("ACIC");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imagens/undraw_building_websites_i78t.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel1.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 72, 890, 530));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1000, 870));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Saida.setBackground(new java.awt.Color(255, 255, 255));
        Saida.setFont(new java.awt.Font("Arial Black", 0, 35)); // NOI18N
        Saida.setForeground(new java.awt.Color(255, 255, 255));
        Saida.setText("x");
        Saida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Saida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaidaMouseClicked(evt);
            }
        });
        jPanel2.add(Saida, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, -10, 70, -1));

        CPlembrarsenha.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        CPlembrarsenha.setForeground(new java.awt.Color(255, 255, 255));
        CPlembrarsenha.setText("esqueceu a senha?");
        CPlembrarsenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CPlembrarsenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CPlembrarsenhaMouseClicked(evt);
            }
        });
        jPanel2.add(CPlembrarsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 160, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bem Vindo !");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 72, 170, 40));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("username:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 80, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Forgot_Password_50px_4.png"))); // NOI18N
        jLabel9.setDoubleBuffered(true);
        jLabel9.setFocusCycleRoot(true);
        jLabel9.setFocusTraversalPolicyProvider(true);
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 50, 50));

        CPsenha.setBackground(new java.awt.Color(102, 102, 225));
        CPsenha.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        CPsenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CPsenha.setPlaceholder("Enter password...");
        CPsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPsenhaActionPerformed(evt);
            }
        });
        jPanel2.add(CPsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 270, -1));

        CPlogin.setBackground(new java.awt.Color(102, 102, 225));
        CPlogin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        CPlogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CPlogin.setPlaceholder("Enter username...");
        CPlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPloginActionPerformed(evt);
            }
        });
        jPanel2.add(CPlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 270, -1));

        Cadastro.setBackground(new java.awt.Color(153, 153, 225));
        Cadastro.setText("Cadastro");
        Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroActionPerformed(evt);
            }
        });
        jPanel2.add(Cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 320, 60));

        Loguin.setBackground(new java.awt.Color(255, 51, 51));
        Loguin.setText("login");
        Loguin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoguinActionPerformed(evt);
            }
        });
        jPanel2.add(Loguin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 320, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Secure_50px (1).png"))); // NOI18N
        jLabel11.setDoubleBuffered(true);
        jLabel11.setFocusCycleRoot(true);
        jLabel11.setFocusTraversalPolicyProvider(true);
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 50, 50));

        rSPanelImage2.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_Account_50px.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage2Layout = new javax.swing.GroupLayout(rSPanelImage2);
        rSPanelImage2.setLayout(rSPanelImage2Layout);
        rSPanelImage2Layout.setHorizontalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        rSPanelImage2Layout.setVerticalGroup(
            rSPanelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(rSPanelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 50, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 550, 880));

        setBounds(0, 0, 1507, 692);
    }// </editor-fold>//GEN-END:initComponents

    private void SaidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaidaMouseClicked
       System.exit(0);
    }//GEN-LAST:event_SaidaMouseClicked

    private void CPsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPsenhaActionPerformed

    private void CPloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPloginActionPerformed

    private void CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastroActionPerformed

    private void LoguinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoguinActionPerformed
      if(CPlogin.getText().toString().equals("usuario")&& CPsenha.getText().toString().equals("1234")){
        JOptionPane.showMessageDialog(null, "Bem Vindo !");
      }else{
       JOptionPane.showMessageDialog(null, "usuario negado !");
      }
    }//GEN-LAST:event_LoguinActionPerformed

    private void CPlembrarsenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CPlembrarsenhaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CPlembrarsenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPlembrarsenha;
    private app.bolivia.swing.JCTextField CPlogin;
    private app.bolivia.swing.JCTextField CPsenha;
    private rojerusan.RSMaterialButtonCircle Cadastro;
    private rojerusan.RSMaterialButtonCircle Loguin;
    private javax.swing.JLabel Saida;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSPanelImage rSPanelImage1;
    private rojerusan.RSPanelImage rSPanelImage2;
    // End of variables declaration//GEN-END:variables
}
